[colors]
background = #282828
background-alt = #373B41
foreground = #ebdbb2
primary = #F0C674
secondary = #8ABEB7
alert = #A54242
disabled = #707880
custom1 = #5983FF
custom2 = #CF5B65
custom3 = #78AB6A
custom4 = #BDB51A
custom5 = #9961AD
custom6 = #DE8050

[bar/mybar]
monitor = ${env:MONITOR:HDMI-A-0}
width = 100%
height = 20pt
radius = 0
; dpi = 96
background = ${colors.background}
foreground = ${colors.foreground}
line-size = 3pt
border-size = 4pt
border-color = #00000000
padding-left = 0
padding-right = 1
module-margin = 1
;separator = 
separator-foreground = ${colors.custom4}

font-0 = "DejaVu Sans Mono:size=11;2"
font-1 = FontAwesome6Free:style=Solid:size=10;2
font-2 = FontAwesome6Free:style=Regular:size=10;2
font-3 = FontAwesome6Brands:style=Regular:size=10;2
font-4 = "Flags Color World:style=Regular:size=15;4"

modules-left = xworkspaces xwindow
modules-center = 
modules-right = vpn-status menu-vpn pulseaudio memory cpu cpu-temp gpu-usage gpu-temp xkeyboard date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

;tray-position = right
;tray-padding = 2

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

[module/xworkspaces]
type = internal/xworkspaces

icon-0 = 1;
icon-1 = 2;
icon-2 = 3;
icon-3 = 4;
icon-4 = 5;
icon-5 = 6;
icon-6 = 7;
icon-7 = 8;
icon-8 = 9;
icon-9 = 10;

label-active = %icon%
;label-active-foreground = ${colors.custom6}
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1
label-occupied = %icon%
label-occupied-padding = 1
label-urgent = %icon%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1
label-empty = %icon%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title%
label-maxlen = 50

[module/filesystem]
type = internal/fs
interval = 25
mount-0 = /
label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio
interval = 2
format-volume = <ramp-volume><label-volume>
ramp-volume-foreground = ${colors.custom1}
label-muted =  muted
ramp-volume-0 = :
ramp-volume-1 = :
ramp-volume-2 = :
click-right = pavucontrol

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
label-layout = %icon%
label-layout-font = 5
layout-icon-0 = ru;r
layout-icon-1 = us;u
label-layout-foreground = ${colors.primary}
label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = ":"
format-prefix-foreground = ${colors.custom2}
label = %used%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = ":"
format-prefix-foreground = ${colors.custom4}
label = %percentage%%

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{F#F0C674}%ifname%%{F-} %essid% %local_ip%

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%

[module/date]
type = internal/date
interval = 1
date = %H:%M
date-alt = %Y-%m-%d %H:%M:%S
label = %date%
label-foreground = ${colors.foreground}

[module/menu-vpn]
type = custom/menu
expand-right = true
format-prefix = :
format-prefix-foreground = ${colors.custom3}
label-open = VPN
label-close = "  "
label-close-foreground = #c71a1a
label-separator = 
menu-0-0 = " hetzner "
menu-0-0-exec = ~/.config/polybar/scripts/vpn_up_hetzner.sh
menu-0-1 = " work_ovpn "
menu-0-1-exec = ~/.config/polybar/scripts/vpn_up_work.sh

[module/vpn-status]
type = custom/script
exec = ~/.config/polybar/scripts/vpn_check.sh
click-left = ~/.config/polybar/scripts/vpn_down.sh
click-right = ~/.config/polybar/scripts/vpn_down.sh
interval = 1

[module/cpu-temp]
type = custom/script
format-prefix-foreground = ${colors.custom4}
exec = ~/.config/polybar/scripts/cpu_temp.sh

[module/gpu-usage]
format-prefix = :
format-prefix-foreground = ${colors.custom5}
interval = 1
type = custom/script
exec = ~/.config/polybar/scripts/gpu_usage.sh

[module/gpu-temp]
type = custom/script
exec = ~/.config/polybar/scripts/gpu_temp.sh

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
