import = ["/home/welqd/.config/alacritty/gruvbox-material-medium.toml"]

[font]
size = 14.0

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[window]
decorations = "full"
# opacity = 0.90
